fix UI avt in profile
aesirxio/aesirx-uikit pull request #135
Opened 2023-09-06 10:10 UTC by lamanhvu62

2023-09-06 10:12 UTC, lamanhvu62 commented
@lunguyenhat

2023-09-06 10:25 UTC, vietredweb requested changes
Please run below scripts before commiting code, to fix the CI @lamanhvu62 
- `yarn lint`
- `yarn format:check` (or you can just install Prettier - Code formatter on Visual Studio Code for automatic check)
- `yarn format:write`

2023-09-06 10:25 UTC, vietredweb commented on src/components/Form/FormDAMImage/index.tsx
> +    console.log(prefersDark)
Please remove debug here @lamanhvu62

2023-09-07 04:04 UTC, lamanhvu62 commented
i fix done @lunguyenhat  @vietredweb

2023-09-07 04:04 UTC, vietredweb approved these changes

2023-09-07 10:42 UTC, vietredweb requested changes
It seems the new commit missing `yarn format:check` and `yarn format:write` @lamanhvu62

2023-09-08 03:40 UTC, vietredweb approved these changes

2023-09-08 09:41 UTC, vietredweb approved these changes

2023-09-11 09:56 UTC, merged